version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️ deps:'
      prefix-development: '⬆️🔨 dev-deps:'
    assignees:
      - "shanpriyan"
    reviewers:
      - "shanpriyan"
    open-pull-requests-limit: 10
    rebase-strategy: auto
